#!/bin/bash

set -e

tbld=$(tput bold)
tred=$(tput setaf 1)
tgrn=$(tput setaf 2)
tmgt=$(tput setaf 5)
trst=$(tput sgr0)
p() { echo -e "\e[K${tbld}${tgrn}-> $1${trst}"; }
e() { echo "${tbld}${tred}-> $1${trst}"; }

function ctrl_c() {
  echo -e "\nExiting install."
  exit 1
}

function press_any_key_to_contine() {
  # -n 1: Read only one character
  # -r: Do not allow backslashes to escape characters
  # -s: Do not echo the input character
  # -p: Display a prompt
  read -n 1 -r -s -p $'Press any key to install, or ctrl+c to abort...\n' key
}

log() {
  # exit if stdin is not connected to a pipe
  [[ -t 0 ]] && { echo "'log' should be used with piped input."}; exit 1; }

  while STDIN= read -r line; do
    printf '\033[2K\r%s' "$line"
  done
}

trap ctrl_c INT

# NOVA ascii art generated by 'toilet'
echo '                          
                            
 [0;1;33;93mm[0m [0;1;32;92mm[0;1;36;96mm[0m    [0;1;35;95mm[0;1;31;91mmm[0m   [0;1;32;92mm[0m   [0;1;34;94mm[0m   [0;1;31;91mm[0;1;33;93mmm[0m  
 [0;1;32;92m#[0;1;36;96m"[0m  [0;1;34;94m#[0m  [0;1;31;91m#"[0m [0;1;33;93m"[0;1;32;92m#[0m  [0;1;36;96m"[0;1;34;94mm[0m [0;1;35;95mm"[0m  [0;1;33;93m"[0m   [0;1;36;96m#[0m 
 [0;1;36;96m#[0m   [0;1;35;95m#[0m  [0;1;33;93m#[0m   [0;1;36;96m#[0m   [0;1;35;95m#m[0;1;31;91m#[0m   [0;1;32;92mm"[0;1;36;96m""[0;1;34;94m#[0m 
 [0;1;34;94m#[0m   [0;1;31;91m#[0m  [0;1;32;92m"#[0;1;36;96mm#[0;1;34;94m"[0m    [0;1;31;91m#[0m    [0;1;36;96m"m[0;1;34;94mm"[0;1;35;95m#[0m 
                            
'                           

p "Nova is for fresh Ubuntu 25.10+ installations only!"
press_any_key_to_contine

p "Installation starting..."

# avoid debconf unable to initialize frontend errors
echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

p "updating apt repositories..."
sudo apt-get update | log
sudo apt-get install -y git | log

p "cloning Nova..."
rm -rf ~/.local/share/nova
git clone -q https://github.com/kalmbach/nova.git ~/.local/share/nova

p "switching to branch: ubuntu-25.10..."
cd ~/.local/share/nova
git fetch -q origin ubuntu-25.10 >/dev/null && git checkout -q ubuntu-25.10>/dev/null
cd --

source ~/.local/share/nova/install.sh

p "Installation complete."
