#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

NOVA_PATH="$(dirname -- "${BASH_SOURCE[0]}")"

# Install required packages
source $NOVA_PATH/install/required/gum.sh > /dev/null

# Check the distribution name and version and abort if incompatible
source $NOVA_PATH/check-version.sh 

# Install applications 
source $NOVA_PATH/install/applications.sh

# Install languages
source $NOVA_PATH/install/languages.sh

# Install fonts
source $NOVA_PATH/install/fonts.sh

# Install dot files
source $NOVA_PATH/install/dotfiles.sh
