#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

export STARTPOINT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
RUNNING_GNOME=$([[ "$XDG_CURRENT_DESKTOP" == *"GNOME"* ]] && echo true || echo false)

# Check the distribution name and version and abort if incompatible
source $STARTPOINT_PATH/check-version.sh 

# Install required packages
source $STARTPOINT_PATH/install/required/gum.sh >/dev/null

# Install terminal tools
source $STARTPOINT_PATH/install/terminal.sh

if $RUNNING_GNOME; then
	# Install desktop tools and tweaks
	source $STARTPOINT_PATH/install/desktop.sh
fi
